baseURL = 'https://www.wire48.net/'
languageCode = 'en-gb'
title = 'wire48.net'
theme = 'terminal'
sectionPagesMenu = 'main'

[languages]
  [languages.en]
    title = "wire48.net"
    [languages.en.params.logo]
      logoText = "wire48.net"
